import type { Metadata } from "next";
import "@styles/globals.scss";
import Header from "@components/Header";
import { DashboardHeader } from "@components/DashboardHeader";
import Footer from "../components/footer";
import { AuthProvider } from "src/Auth/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const LayoutContent = ({ children }: { children: React.ReactNode }) => {
  return <main className="contentContainer">{children}</main>;
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className="layoutContainer">
          {/* ✅ Fixed Header */}
          <div className="headerContainer">
            <Header />
          </div>

          {/* ✅ Fixed Dashboard Header (only if logged in) */}
          <div className="dashboardHeaderContainer">
            <DashboardHeader />
          </div>

          {/* ✅ Scrollable Content */}
          <LayoutContent>{children}</LayoutContent>

          {/* ✅ Fixed Footer */}
          <div className="footerContainer">
            <Footer />
          </div>
        </body>
      </html>
    </AuthProvider>
  );
}
